apiVersion: v1
kind: Service
metadata:
  name: wildfly
  labels:
    app: wildfly
spec:
  selector:
    app: wildfly
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: management
    port: 9990
    targetPort: 9990